[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.6.4"
quilt_loader = "0.18.2"
feather_mappings = "1.6.4+build.1"
nests = "1.6.4+build.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
feather_mappings = { module = "net.ornithemc:feather", version.ref = "feather_mappings" }
nests = { module = "net.ornithemc:nests", version.ref = "nests" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.1.+" }
ploceus = { id = "ploceus", version = "1.1.+" }
